---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: harbor
      version: 16.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
