
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: unsupported
spec:
  url: ${helmMirrorURL:=oci://registry-1.docker.io/bitnamicharts}
  interval: 5m
